<?php

namespace App\Filament\Resources\FollowUpSurveys\Tables;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\ViewAction;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class FollowUpSurveysTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('follow_up_type')
                    ->searchable(),
                TextColumn::make('enumerator_name')
                    ->searchable(),
                TextColumn::make('follow_up_date')
                    ->date()
                    ->sortable(),
                TextColumn::make('key_respondent_name')
                    ->searchable(),
                TextColumn::make('key_respondent_position')
                    ->searchable(),
                TextColumn::make('key_respondent_contact')
                    ->searchable(),
                TextColumn::make('wusc_official_name')
                    ->searchable(),
                TextColumn::make('scheme_code')
                    ->searchable(),
                TextColumn::make('total_households')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('total_taps')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('functional_taps')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('non_functional_taps_closure')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('non_functional_taps_no_water')
                    ->numeric()
                    ->sortable(),
                IconColumn::make('is_mus')
                    ->boolean(),
                TextColumn::make('households_with_kitchen_gardens')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('avg_kitchen_garden_size')
                    ->numeric()
                    ->sortable(),
                IconColumn::make('is_wusc')
                    ->boolean(),
                TextColumn::make('total_wusc_officials')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('female_officials')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('dalit_officials')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('janajati_officials')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('wusc_chairperson_name')
                    ->searchable(),
                TextColumn::make('wusc_chairperson_contact')
                    ->searchable(),
                TextColumn::make('wusc_vice_chairperson_name')
                    ->searchable(),
                TextColumn::make('wusc_vice_chairperson_contact')
                    ->searchable(),
                TextColumn::make('wusc_secretary_name')
                    ->searchable(),
                TextColumn::make('wusc_secretary_contact')
                    ->searchable(),
                TextColumn::make('wusc_treasurer_name')
                    ->searchable(),
                TextColumn::make('wusc_treasurer_contact')
                    ->searchable(),
                IconColumn::make('is_caretaker')
                    ->boolean(),
                TextColumn::make('caretaker_name')
                    ->searchable(),
                TextColumn::make('caretaker_contact')
                    ->searchable(),
                IconColumn::make('caretaker_regular')
                    ->boolean(),
                IconColumn::make('caretaker_trained')
                    ->boolean(),
                IconColumn::make('caretaker_paid')
                    ->boolean(),
                TextColumn::make('caretaker_honorarium')
                    ->numeric()
                    ->sortable(),
                IconColumn::make('is_wusc_registered')
                    ->boolean(),
                TextColumn::make('registration_number')
                    ->searchable(),
                IconColumn::make('ag_assembly_regular')
                    ->boolean(),
                TextColumn::make('last_general_assembly_date')
                    ->date()
                    ->sortable(),
                IconColumn::make('meetings_regular')
                    ->boolean(),
                TextColumn::make('meeting_frequency')
                    ->searchable(),
                TextColumn::make('meetings_last_year')
                    ->numeric()
                    ->sortable(),
                IconColumn::make('wusc_reformed')
                    ->boolean(),
                TextColumn::make('record_minutes')
                    ->searchable(),
                TextColumn::make('record_income_expense')
                    ->searchable(),
                IconColumn::make('has_om_plan')
                    ->boolean(),
                IconColumn::make('fund_collection_regular')
                    ->boolean(),
                TextColumn::make('monthly_tariff')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('total_om_fund')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('status_intake')
                    ->searchable(),
                TextColumn::make('status_pipeline')
                    ->searchable(),
                TextColumn::make('status_rvt')
                    ->searchable(),
                TextColumn::make('status_tap_stands')
                    ->searchable(),
                TextColumn::make('status_other_structures')
                    ->searchable(),
                TextColumn::make('photo_1')
                    ->searchable(),
                TextColumn::make('photo_2')
                    ->searchable(),
                TextColumn::make('latitude')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('longitude')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->recordActions([
                ViewAction::make(),
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}
