# .nixpacks.toml

# Define setup phase to install necessary packages
[phases.setup]
nixPkgs = ['nodejs-20_x', 'composer']

# Define build phase to install dependencies and build assets
[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "npm run build",
    "php artisan config:clear",
    "php artisan route:clear",
    "php artisan view:clear",
    "php artisan cache:clear",
    "php artisan config:cache"
]

# Define start phase to serve the application
[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

# Define web root directory
[web]
root = "public"
