<?php

namespace App\Filament\Resources\FollowUpSurveys\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class FollowUpSurveyInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('follow_up_type'),
                TextEntry::make('enumerator_name'),
                TextEntry::make('follow_up_date')
                    ->date(),
                TextEntry::make('key_respondent_name'),
                TextEntry::make('key_respondent_position'),
                TextEntry::make('key_respondent_contact'),
                TextEntry::make('wusc_official_name'),
                TextEntry::make('scheme_code'),
                TextEntry::make('total_households')
                    ->numeric(),
                TextEntry::make('total_taps')
                    ->numeric(),
                TextEntry::make('functional_taps')
                    ->numeric(),
                TextEntry::make('non_functional_taps_closure')
                    ->numeric(),
                TextEntry::make('non_functional_taps_no_water')
                    ->numeric(),
                IconEntry::make('is_mus')
                    ->boolean(),
                TextEntry::make('households_with_kitchen_gardens')
                    ->numeric(),
                TextEntry::make('avg_kitchen_garden_size')
                    ->numeric(),
                IconEntry::make('is_wusc')
                    ->boolean(),
                TextEntry::make('total_wusc_officials')
                    ->numeric(),
                TextEntry::make('female_officials')
                    ->numeric(),
                TextEntry::make('dalit_officials')
                    ->numeric(),
                TextEntry::make('janajati_officials')
                    ->numeric(),
                TextEntry::make('wusc_chairperson_name'),
                TextEntry::make('wusc_chairperson_contact'),
                TextEntry::make('wusc_vice_chairperson_name'),
                TextEntry::make('wusc_vice_chairperson_contact'),
                TextEntry::make('wusc_secretary_name'),
                TextEntry::make('wusc_secretary_contact'),
                TextEntry::make('wusc_treasurer_name'),
                TextEntry::make('wusc_treasurer_contact'),
                IconEntry::make('is_caretaker')
                    ->boolean(),
                TextEntry::make('caretaker_name'),
                TextEntry::make('caretaker_contact'),
                IconEntry::make('caretaker_regular')
                    ->boolean(),
                IconEntry::make('caretaker_trained')
                    ->boolean(),
                IconEntry::make('caretaker_paid')
                    ->boolean(),
                TextEntry::make('caretaker_honorarium')
                    ->numeric(),
                IconEntry::make('is_wusc_registered')
                    ->boolean(),
                TextEntry::make('registration_number'),
                IconEntry::make('ag_assembly_regular')
                    ->boolean(),
                TextEntry::make('last_general_assembly_date')
                    ->date(),
                IconEntry::make('meetings_regular')
                    ->boolean(),
                TextEntry::make('meeting_frequency'),
                TextEntry::make('meetings_last_year')
                    ->numeric(),
                IconEntry::make('wusc_reformed')
                    ->boolean(),
                TextEntry::make('record_minutes'),
                TextEntry::make('record_income_expense'),
                IconEntry::make('has_om_plan')
                    ->boolean(),
                IconEntry::make('fund_collection_regular')
                    ->boolean(),
                TextEntry::make('monthly_tariff')
                    ->numeric(),
                TextEntry::make('total_om_fund')
                    ->numeric(),
                TextEntry::make('status_intake'),
                TextEntry::make('status_pipeline'),
                TextEntry::make('status_rvt'),
                TextEntry::make('status_tap_stands'),
                TextEntry::make('status_other_structures'),
                TextEntry::make('photo_1'),
                TextEntry::make('photo_2'),
                TextEntry::make('latitude')
                    ->numeric(),
                TextEntry::make('longitude')
                    ->numeric(),
                TextEntry::make('created_at')
                    ->dateTime(),
                TextEntry::make('updated_at')
                    ->dateTime(),
            ]);
    }
}
