<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('schemes', function (Blueprint $table) {
            $table->id();

            // -------------------
            // Location / Address
            // -------------------
            $table->string('province');
            $table->string('district');
            $table->string('mun')->comment('Municipality');
            $table->integer('ward_no')->comment('Ward number');

            // -------------------
            // Identification
            // -------------------
            $table->string('scheme_code')->unique()->comment('Unique autogenerated scheme code');
            $table->string('scheme_code_user')->nullable();
            $table->string('scheme_name');
            $table->string('scheme_name_np')->nullable()->comment('Scheme name in Nepali');

            // -------------------
            // Sub Schemes
            // -------------------

            $table->string('no_of_sub_schemes')->default('0')->nullable()->comment('Scheme name in Nepali');

            // -------------------
            // Collaborator
            // -------------------
            $table->json('collaborator')->nullable();

            // -------------------
            // Type & Classification
            // -------------------
            $table->string('scheme_sector')->nullable()->comment('WASH / WS / SAN');
            $table->string('scheme_construction_type')->default('New')->comment('New / Rehab');
            $table->string('scheme_technology')->nullable()->comment('Gravity, Solar Lift');

            // -------------------
            // Timing & Dates
            // -------------------
            $table->date('started_date')->nullable()->comment('Start date of construction');
            $table->date('planned_completion_date')->nullable()->comment('Planned completion date');
            $table->date('actual_completed_date')->nullable()->comment('Actual completion date');

            // -------------------
            // Status Flags
            // -------------------
            $table->boolean('source_registration_status')->default(false)->comment('Is the source registered?');
            $table->boolean('source_conservation')->default(false)->comment('Source conservation implemented?');
            $table->string('progress_status')->nullable()->comment('Progress status: Ongoing / Completed / Dropout');
            $table->text('justification_for_delay')->nullable()->comment('Reason for any delay in progress');

            // -------------------
            // Standard Laravel
            // -------------------
            $table->softDeletes();
            $table->timestamps();

            // -------------------
            // Indexes (Optional but recommended)
            // -------------------
            $table->index('province');
            $table->index('district');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('schemes');
    }
};
