<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('schemes', function (Blueprint $table) {
            $table->id();

            // -------------------
            // Location / Address
            // -------------------
            $table->string('province')->comment('Province code or name');
            $table->string('district')->comment('District code or name');
            $table->string('mun')->comment('Municipality / Rural Municipality');
            $table->integer('ward_no')->comment('Ward number');

            // -------------------
            // Identification
            // -------------------
            $table->string('scheme_code')->unique()->comment('Unique autogenerated scheme code');
            $table->string('scheme_name')->comment('Scheme name in English');
            $table->string('scheme_name_np')->nullable()->comment('Scheme name in Nepali');

            // -------------------
            // Type & Classification
            // -------------------
            $table->string('sector')->nullable()->comment('Sector: WS / SAN / etc.');
            $table->string('scheme_technology')->nullable()->comment('Technology type, e.g., Gravity, Solar Lift');
            $table->string('scheme_type')->default('DWS')->comment('Scheme type: New / Rehab / DWS / MUS');
            $table->string('scheme_construction_type')->default('New')->comment('Construction type, default New');

            // -------------------
            // Timing & Dates
            // -------------------
            $table->year('scheme_start_year')->comment('Year scheme started');
            $table->date('completion_date')->nullable()->comment('Expected or actual completion date');
            $table->date('agreement_signed_date')->nullable()->comment('Agreement signed date');
            $table->date('schedule_end_date')->nullable()->comment('Scheduled end date');
            $table->date('started_date')->nullable()->comment('Start date of construction');
            $table->date('planned_completion_date')->nullable()->comment('Planned completion date');
            $table->date('actual_completed_date')->nullable()->comment('Actual completion date');

            // -------------------
            // Status Flags
            // -------------------
            $table->boolean('source_registration_status')->default(false)->comment('Is the source registered?');
            $table->boolean('source_conservation')->default(false)->comment('Source conservation implemented?');
            $table->boolean('no_subscheme')->default(false)->comment('Indicates if there are no subschemes');
            $table->string('progress_status')->nullable()->comment('Progress status: Ongoing / Completed / Dropout');
            $table->text('justification_for_delay')->nullable()->comment('Reason for any delay in progress');

            // -------------------
            // Standard Laravel
            // -------------------
            $table->softDeletes();
            $table->timestamps();

            // -------------------
            // Indexes (Optional but recommended)
            // -------------------
            $table->index('province');
            $table->index('district');
            $table->index('scheme_type');
            $table->index('scheme_start_year');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('schemes');
    }
};
